import type {Locale} from '../types';
import {scoreDetailTranslation} from './cubeScoreDetails';
import {testResetTranslation} from './testReset';
export const testKeys=['test.start','test.take','test.continue','test.question','test.intro','test.final','test.memoGuide','test.next','test.finished','test.retake','test.repeat','test.discard','cubeScore.details','cubeScore.notMeasured','cubeScore.analyzing','cubeScore.disclaimer','cubeScore.method','test.home','test.back','test.hint','test.attempts','test.restart','test.resume','test.pause'] as const;
const copy:Record<Locale,readonly string[]>={
 en:['START TEST','TAKE THE CUBE TEST','CONTINUE TEST','QUESTION {n} / 5','5 challenges · About 15 min. Explore, remember and reconstruct five new shapes. Accuracy, time, hints and restarts determine your game score. Memo use has no direct penalty.','FINAL CHALLENGE','The final challenge is a long route. Use CUBE MEMO to reconstruct the path you explored.','NEXT QUESTION','CHALLENGE COMPLETE','RETAKE CUBE TEST','Retaking Set A uses the same puzzles. Familiarity may affect your score. Home shows your best valid score.','Discard the unfinished test and start again?','DETAILS','NOT MEASURED','ANALYZING…','CUBE SCORE is an in-game performance score unique to i CUBE TEST.','Calculated from question difficulty, accuracy and effective solve time, including Memo and answer time.','HOME','BACK','Hint','Attempts','RESTART QUESTION','RESUME','PAUSE'],
 ja:['テスト開始','CUBE TESTを受ける','テストを続ける','QUESTION {n} / 5','新しい5問に挑戦します。目安は約15分です。難易度・正確さ・時間・ヒント・再スタートからゲームスコアを算出します。メモ利用そのものは減点しません。','FINAL CHALLENGE','最後は長いルートです。CUBE MEMOを使って、通ってきた形を組み立ててみましょう。','次の問題','チャレンジ終了','CUBE TESTを再受験','再受験は同じSet Aです。問題への慣れがスコアに影響する場合があります。Homeにはベストスコアを表示します。','途中のテストを破棄して最初から始めますか？','詳細','未測定','集計中…','CUBE SCOREはi CUBE TEST独自のゲームスコアです。','問題の難易度・回答の正確さ・実際に考えていた時間から算出します。メモ・回答中の時間も含みます。','ホーム','戻る','ヒント','回答回数','問題を再スタート','再開','一時停止'],
 ko:['테스트 시작','CUBE TEST 도전','테스트 계속','문제 {n} / 5','새로운 문제 5개 · 약 15분. 난이도, 정확도, 시간, 힌트와 재시작으로 게임 점수를 계산합니다. 메모 사용 자체는 감점하지 않습니다.','마지막 도전','마지막은 긴 경로입니다. CUBE MEMO로 지나온 경로의 모양을 만들어 보세요.','다음 문제','도전 종료','CUBE TEST 다시 도전','재도전은 같은 Set A입니다. 익숙함이 점수에 영향을 줄 수 있습니다. 홈에는 최고 점수가 표시됩니다.','진행 중인 테스트를 버리고 다시 시작할까요?','상세','미측정','집계 중…','CUBE SCORE는 i CUBE TEST만의 게임 점수입니다.','문제 난이도, 정확도와 풀이 시간으로 계산합니다. 메모와 답변 시간도 포함합니다.','홈','뒤로','힌트','답변 횟수','문제 재시작','계속','일시 정지'],
 'zh-CN':['开始测试','参加 CUBE TEST','继续测试','第 {n} / 5 题','5道新题 · 约15分钟。根据难度、准确度、时间、提示和重试计算游戏分数。使用备忘本身不扣分。','最终挑战','最后是一条长路线。使用 CUBE MEMO 重建你走过的路线。','下一题','挑战结束','重新参加 CUBE TEST','重测使用同一套 Set A。熟悉题目可能影响分数。主页显示最佳有效分数。','放弃未完成的测试并重新开始？','详情','未测试','正在汇总…','CUBE SCORE 是 i CUBE TEST 独有的游戏分数。','根据题目难度、准确度和解题时间计算，包括备忘与回答时间。','主页','返回','提示','回答次数','重新开始本题','继续','暂停'],
 'zh-TW':['開始測試','參加 CUBE TEST','繼續測試','第 {n} / 5 題','5道新題 · 約15分鐘。依難度、準確度、時間、提示和重試計算遊戲分數。使用備忘本身不扣分。','最終挑戰','最後是一條長路線。使用 CUBE MEMO 重建你走過的路線。','下一題','挑戰結束','重新參加 CUBE TEST','重測使用同一套 Set A。熟悉題目可能影響分數。首頁顯示最佳有效分數。','放棄未完成的測試並重新開始？','詳情','未測試','正在彙整…','CUBE SCORE 是 i CUBE TEST 獨有的遊戲分數。','依題目難度、準確度和解題時間計算，包括備忘與回答時間。','首頁','返回','提示','回答次數','重新開始本題','繼續','暫停'],
 es:['INICIAR TEST','HACER CUBE TEST','CONTINUAR TEST','PREGUNTA {n} / 5','5 retos nuevos · Unos 15 min. La dificultad, precisión, tiempo, pistas y reinicios determinan la puntuación. Usar el memo no penaliza por sí mismo.','RETO FINAL','El último reto es una ruta larga. Usa CUBE MEMO para reconstruir el recorrido explorado.','SIGUIENTE PREGUNTA','RETO TERMINADO','REPETIR CUBE TEST','Se repite el mismo Set A. Conocer los problemas puede influir en la puntuación. Inicio muestra tu mejor resultado válido.','¿Descartar el test pendiente y empezar de nuevo?','DETALLES','SIN MEDIR','CALCULANDO…','CUBE SCORE es una puntuación del juego exclusiva de i CUBE TEST.','Se calcula con dificultad, precisión y tiempo de resolución, incluidos el memo y las respuestas.','INICIO','VOLVER','Pista','Intentos','REINICIAR PREGUNTA','CONTINUAR','PAUSA'],
 pt:['INICIAR TESTE','FAZER CUBE TEST','CONTINUAR TESTE','QUESTÃO {n} / 5','5 desafios novos · Cerca de 15 min. Dificuldade, precisão, tempo, dicas e reinícios determinam a pontuação. Usar o memo não causa penalização direta.','DESAFIO FINAL','O último desafio é uma rota longa. Use CUBE MEMO para reconstruir o caminho explorado.','PRÓXIMA QUESTÃO','DESAFIO CONCLUÍDO','REPETIR CUBE TEST','O teste repete o mesmo Set A. A familiaridade pode afetar a pontuação. O início mostra o melhor resultado válido.','Descartar o teste em curso e recomeçar?','DETALHES','NÃO MEDIDO','CALCULANDO…','CUBE SCORE é uma pontuação de jogo exclusiva do i CUBE TEST.','Calculada pela dificuldade, precisão e tempo de resolução, incluindo memo e respostas.','INÍCIO','VOLTAR','Dica','Tentativas','REINICIAR QUESTÃO','CONTINUAR','PAUSA'],
 de:['TEST STARTEN','CUBE TEST SPIELEN','TEST FORTSETZEN','FRAGE {n} / 5','5 neue Aufgaben · Etwa 15 Min. Schwierigkeit, Genauigkeit, Zeit, Hinweise und Neustarts bestimmen den Spielstand. Memo-Nutzung wird nicht direkt bestraft.','LETZTE AUFGABE','Die letzte Aufgabe ist eine lange Route. Baue den erkundeten Weg mit CUBE MEMO nach.','NÄCHSTE FRAGE','AUFGABE BEENDET','CUBE TEST WIEDERHOLEN','Die Wiederholung nutzt dasselbe Set A. Vertrautheit kann die Punktzahl beeinflussen. Auf der Startseite steht dein bester gültiger Wert.','Den laufenden Test verwerfen und neu beginnen?','DETAILS','NOCH NICHT ERMITTELT','AUSWERTUNG…','CUBE SCORE ist ein eigener Spielleistungswert von i CUBE TEST.','Berechnet aus Schwierigkeit, Genauigkeit und Lösungszeit, einschließlich Memo- und Antwortzeit.','STARTSEITE','ZURÜCK','Hinweis','Versuche','FRAGE NEU STARTEN','FORTSETZEN','PAUSE'],
 fr:['COMMENCER LE TEST','PASSER CUBE TEST','REPRENDRE LE TEST','QUESTION {n} / 5','5 nouveaux défis · Environ 15 min. Difficulté, précision, temps, indices et redémarrages déterminent le score. Le memo ne donne aucune pénalité directe.','DÉFI FINAL','Le dernier défi est un long parcours. Utilisez CUBE MEMO pour reconstruire le chemin exploré.','QUESTION SUIVANTE','DÉFI TERMINÉ','REPASSER CUBE TEST','Le test reprend le même Set A. La familiarité peut influencer le score. L’accueil affiche votre meilleur résultat valide.','Abandonner le test en cours et recommencer ?','DÉTAILS','NON MESURÉ','CALCUL EN COURS…','CUBE SCORE est un score de jeu propre à i CUBE TEST.','Calculé selon la difficulté, la précision et le temps de résolution, memo et réponses compris.','ACCUEIL','RETOUR','Indice','Tentatives','RECOMMENCER LA QUESTION','REPRENDRE','PAUSE'],
};
const seeResults:Record<Locale,string>={en:'SEE TEST RESULTS',ja:'テスト結果を見る',ko:'테스트 결과 보기','zh-CN':'查看测试结果','zh-TW':'查看測試結果',es:'VER RESULTADOS DEL TEST',pt:'VER RESULTADOS DO TESTE',de:'TESTERGEBNIS ANSEHEN',fr:'VOIR LES RÉSULTATS DU TEST'};
export function cubeTestTranslation(locale:Locale,key:string){if(key==='test.seeResults')return seeResults[locale];const i=(testKeys as readonly string[]).indexOf(key);return i<0?(testResetTranslation(locale,key)??scoreDetailTranslation(locale,key)):copy[locale][i];}
