import {advancedTranslation} from './advanced';
import {cubeTestTranslation} from './cubeTest';
import type {Locale} from '../types'; import {loadLocale,saveLocale} from './languageStore';
import {how,howKeys} from './how';
import {controls,controlsKeys} from './controls';
import {answerPrompts} from './answerPrompt';
import {responsiveTranslation} from './responsive';
import {memoTranslation} from './memo';
import {memoHelpTranslation} from './memoHelp';
export const LANGUAGE_NAMES:Record<Locale,string>={en:'English',ja:'日本語','zh-CN':'简体中文','zh-TW':'繁體中文',ko:'한국어',es:'Español',pt:'Português',de:'Deutsch',fr:'Français'};
type Dict=Record<string,string>;
const en:Dict={'home.title':'i CUBE TEST','home.tagline':'THINK IN THREE DIMENSIONS.','home.mainCopy1':'Explore. Remember. See the shape.','home.mainCopy2':'Put your spatial awareness to the test.','home.continue':'CONTINUE','home.continueSub':'RESUME PROGRESS','home.newGame':'NEW GAME','home.newGameSub':'START FROM STAGE 1','home.stageSelect':'STAGE SELECT','home.stageSelectSub':'CHOOSE A STAGE','home.howToPlay':'HOW TO PLAY','home.howToPlaySub':'LEARN THE RULES','home.playerProgress':'PLAYER PROGRESS','home.progress':'PROGRESS','home.nextStage':'NEXT STAGE','home.bestTime':'BEST TIME','home.totalTime':'TOTAL TIME','game.time':'TIME','game.lookUp':'↑ LOOK UP','game.menu':'MENU','game.answer':'ANSWER POINT · E','game.thirdPerson':'THIRD PERSON · V','game.pov':'POV · V','answer.title':'SELECT THE CORRECT SHAPE','answer.remainingAttempts':'REMAINING CHANCES','answer.submit':'SUBMIT ANSWER','answer.backToExploration':'BACK TO EXPLORATION','result.correct':'CORRECT!','result.stageClear':'STAGE {stage} CLEAR','result.time':'TIME','result.attempts':'ATTEMPTS','result.nextStage':'NEXT STAGE','result.retry':'RETRY','result.stageSelect':'STAGE SELECT','common.back':'BACK','how.title':'HOW TO PLAY'};
const translations:Record<Locale,Dict>={en,ja:{...en,'home.mainCopy1':'探索して、記憶して、見抜け。','home.mainCopy2':'君の空間把握能力が試される。','home.continue':'続ける','home.newGame':'新しいゲーム','home.stageSelect':'ステージ選択','home.howToPlay':'遊び方','home.playerProgress':'プレイ進捗','game.lookUp':'↑ 見上げる','game.menu':'メニュー','game.answer':'回答ポイント · E','answer.title':'正しい形を選択','answer.submit':'回答する','common.back':'戻る','how.title':'遊び方'},'zh-CN':{...en,'home.mainCopy1':'探索、记忆、看清形状。','home.mainCopy2':'挑战你的空间认知能力。','home.continue':'继续游戏','home.newGame':'新游戏','home.stageSelect':'选择关卡','home.howToPlay':'玩法说明','home.playerProgress':'游戏进度','how.title':'玩法说明'},'zh-TW':{...en,'home.mainCopy1':'探索、記憶、看清形狀。','home.mainCopy2':'挑戰你的空間認知能力。','home.continue':'繼續遊戲','home.newGame':'新遊戲','home.stageSelect':'選擇關卡','home.howToPlay':'玩法說明','home.playerProgress':'遊戲進度','how.title':'玩法說明'},ko:{...en,'home.continue':'계속하기','home.newGame':'새 게임','home.stageSelect':'스테이지 선택','home.howToPlay':'플레이 방법','home.mainCopy1':'탐색하고, 기억하고, 꿰뚫어 봐.','home.mainCopy2':'당신의 공간 지각 능력을 시험하세요.','how.title':'플레이 방법'},es:{...en,'home.mainCopy1':'Explora. Recuerda. Descubre la forma.','home.mainCopy2':'Pon a prueba tu percepción espacial.','home.continue':'CONTINUAR','home.newGame':'NUEVA PARTIDA','home.stageSelect':'SELECCIONAR FASE','home.howToPlay':'CÓMO JUGAR','home.playerProgress':'PROGRESO','how.title':'CÓMO JUGAR'},pt:{...en,'home.mainCopy1':'Explore. Lembre-se. Descubra a forma.','home.mainCopy2':'Teste a sua perceção espacial.','home.continue':'CONTINUAR','home.newGame':'NOVO JOGO','home.stageSelect':'SELECIONAR FASE','home.howToPlay':'COMO JOGAR','home.playerProgress':'PROGRESSO','how.title':'COMO JOGAR'},de:{...en,'home.mainCopy1':'Erkunde. Merke. Erkenne die Form.','home.mainCopy2':'Teste dein räumliches Vorstellungsvermögen.','home.continue':'FORTSETZEN','home.newGame':'NEUES SPIEL','home.stageSelect':'LEVEL AUSWÄHLEN','home.howToPlay':'SPIELANLEITUNG','home.playerProgress':'SPIELFORTSCHRITT','how.title':'SPIELANLEITUNG'},fr:{...en,'home.mainCopy1':'Explore. Mémorise. Trouve la forme.','home.mainCopy2':'Mets ta perception spatiale à l’épreuve.','home.continue':'CONTINUER','home.newGame':'NOUVELLE PARTIE','home.stageSelect':'CHOISIR UN NIVEAU','home.howToPlay':'COMMENT JOUER','home.playerProgress':'PROGRESSION','how.title':'COMMENT JOUER'}};
let current=loadLocale(); export const locale=()=>current; export function setLocale(l:Locale){current=l;saveLocale(l);document.documentElement.lang=l;}
export function t(key:string,vars:Record<string,string|number>={}):string {const i=(howKeys as readonly string[]).indexOf(key),c=controlsKeys.indexOf(key);let s=cubeTestTranslation(current,key)??advancedTranslation(current,key)??memoHelpTranslation(current,key)??memoTranslation(current,key)??responsiveTranslation(current,key)??(key==='game.answerPrompt'?answerPrompts[current]?.desktop??answerPrompts.en.desktop:key==='game.answerTouch'?answerPrompts[current]?.touch??answerPrompts.en.touch:c>=0?controls[current]?.[c]??controls.en[c]:i>=0?how[current]?.[i]??how.en[i]:translations[current]?.[key]??en[key])??''; return s.replace(/\{(\w+)\}/g,(_,k)=>String(vars[k]??''));}
export {SUPPORTED_LOCALES} from './detectLanguage';



