import type {Locale} from '../types';
export const memoKeys=['subtitle','intro','stock.title','stock.drag','place.single','place.continuous','color.title','color.note','undo','redo','delete','deleteAll','camera.reset','display.title','display.normal','display.wireframe','display.hideColors','help.title','help.drag','help.face','help.orbit','help.zoom','help.select','hint.title','hint.body','hint.locked','hint.available','hint.used','close','workspace','error','white','navy','blue','cyan','lightblue'] as const;
export const memoValues:Record<Locale,readonly string[]>={
 en:['Arrange the cubes you discover to remember the shape.','Drag to recreate a miniature of the stage.','CUBE STOCK','Drag this cube onto the workspace.','Single placement','Continuous placement','MEMO COLORS','Colors are notes only, not part of the answer.','Undo','Redo','Delete selected','Delete all','Reset rotation','DISPLAY MODE','Normal','Wireframe only','Hide memo colors','CONTROLS','Drag: place a cube','Face drag: extend along that face','Right / empty touch drag: orbit','Wheel / pinch: zoom','Click / tap: select a cube','ABOUT HINTS','After an incorrect answer, a hint becomes available once. Only correct cubes already in your memo glow. Other cubes stay white; missing cubes are not shown.','Hint locked','Use hint','Hint used','Close memo','3D workspace','3D could not start. Close the memo and try again.','White','Deep navy','Blue','Cyan','Light cyan'],
 ja:['見つけた立方体を並べて、形をメモしましょう。','ドラッグしてステージのミニチュアを再現します。','立方体ストック','立方体を右のワークスペースへドラッグします。','1個配置','連続配置','カラー（メモ用）','色はメモ用です。正解判定には影響しません。','元に戻す','やり直す','選択を削除','すべて削除','回転をリセット','表示モード','通常','格子線のみ','メモの色を非表示','操作方法','ドラッグ：立方体を配置','面にドラッグ：その方向へ連続配置','右ドラッグ／空白をタッチドラッグ：回転','ホイール／ピンチ：ズーム','クリック／タップ：立方体を選択','ヒントについて','回答を間違えると、ヒントを1回使用できます。メモの正しい位置の立方体だけが光ります。その他は白いまま、不足分は表示しません。','ヒント（未解放）','ヒントを使う','ヒント使用済み','このメモを閉じる','3Dワークスペース','3Dを開始できませんでした。メモを閉じて再度お試しください。','白','濃紺','青','シアン','ライトシアン'],
 ko:['찾아낸 큐브를 놓아 모양을 메모하세요.','드래그하여 스테이지의 미니어처를 만드세요.','큐브 보관함','큐브를 작업 공간으로 드래그하세요.','하나씩 놓기','연속 배치','메모 색상','색상은 메모용이며 정답 판정에 영향을 주지 않습니다.','실행 취소','다시 실행','선택 삭제','모두 삭제','회전 초기화','표시 모드','일반','윤곽선만','메모 색 숨기기','조작 방법','드래그: 큐브 배치','면 드래그: 해당 방향으로 연속 배치','우클릭 / 빈 곳 터치 드래그: 회전','휠 / 핀치: 확대·축소','클릭 / 탭: 큐브 선택','힌트 안내','오답 후 힌트를 한 번 사용할 수 있습니다. 메모에서 위치가 맞는 큐브만 빛납니다. 나머지는 흰색으로 남고, 빠진 큐브는 표시하지 않습니다.','힌트 잠김','힌트 사용','힌트 사용 완료','메모 닫기','3D 작업 공간','3D를 시작할 수 없습니다. 메모를 닫고 다시 시도하세요.','흰색','짙은 남색','파란색','시안','밝은 시안'],
 'zh-CN':['摆放发现的立方体，记下空间形状。','拖动立方体，重现关卡的微缩模型。','立方体库','将立方体拖到工作区。','单个放置','连续放置','备忘颜色','颜色仅用于备忘，不影响答案判定。','撤销','重做','删除所选','全部删除','重置旋转','显示模式','正常','仅显示边框','隐藏备忘颜色','操作方法','拖动：放置立方体','拖动表面：沿该方向连续放置','右键 / 空白处触摸拖动：旋转','滚轮 / 双指缩放：缩放','点击：选择立方体','关于提示','答错后可使用一次提示。只有备忘中位置正确的立方体会发光。其他保持白色，缺少的立方体不会显示。','提示未解锁','使用提示','提示已使用','关闭备忘','3D工作区','无法启动3D。请关闭备忘后重试。','白色','深蓝','蓝色','青色','浅青色'],
 'zh-TW':['擺放發現的立方體，記下空間形狀。','拖曳立方體，重現關卡的微縮模型。','立方體庫','將立方體拖曳到工作區。','單個放置','連續放置','備忘顏色','顏色僅用於備忘，不影響答案判定。','復原','重做','刪除所選','全部刪除','重設旋轉','顯示模式','一般','僅顯示邊框','隱藏備忘顏色','操作方法','拖曳：放置立方體','拖曳表面：沿該方向連續放置','右鍵 / 空白處觸控拖曳：旋轉','滾輪 / 雙指縮放：縮放','點選：選擇立方體','關於提示','答錯後可使用一次提示。只有備忘中位置正確的立方體會發光。其他保持白色，缺少的立方體不會顯示。','提示未解鎖','使用提示','提示已使用','關閉備忘','3D工作區','無法啟動3D。請關閉備忘後重試。','白色','深藍','藍色','青色','淺青色'],
 es:['Coloca los cubos que descubras para recordar la forma.','Arrastra para recrear una miniatura de la fase.','RESERVA DE CUBOS','Arrastra el cubo al área de trabajo.','Colocar uno','Colocación continua','COLORES DE NOTAS','Los colores son notas y no afectan a la respuesta.','Deshacer','Rehacer','Eliminar selección','Eliminar todo','Restablecer giro','VISTA','Normal','Solo contornos','Ocultar colores','CONTROLES','Arrastrar: colocar un cubo','Arrastrar una cara: extender en esa dirección','Arrastre derecho / zona vacía táctil: girar','Rueda / pellizco: zoom','Clic / toque: seleccionar','SOBRE LAS PISTAS','Tras fallar, puedes usar una pista una vez. Solo brillan los cubos bien colocados de tu nota. Los demás quedan blancos; no aparecen los que faltan.','Pista bloqueada','Usar pista','Pista usada','Cerrar nota','Área 3D','No se pudo iniciar 3D. Cierra la nota e inténtalo de nuevo.','Blanco','Azul marino','Azul','Cian','Cian claro'],
 pt:['Coloque os cubos descobertos para memorizar a forma.','Arraste para recriar uma miniatura da fase.','RESERVA DE CUBOS','Arraste o cubo para a área de trabalho.','Colocar um','Colocação contínua','CORES DA NOTA','As cores são anotações e não afetam a resposta.','Desfazer','Refazer','Apagar seleção','Apagar tudo','Repor rotação','VISUALIZAÇÃO','Normal','Apenas contornos','Ocultar cores','CONTROLOS','Arrastar: colocar cubo','Arrastar face: prolongar nessa direção','Arrastar com botão direito / área vazia: rodar','Roda / pinça: zoom','Clique / toque: selecionar','SOBRE AS DICAS','Após uma resposta errada, pode usar uma dica uma vez. Só brilham os cubos bem colocados na nota. Os outros ficam brancos; os que faltam não aparecem.','Dica bloqueada','Usar dica','Dica usada','Fechar nota','Área 3D','Não foi possível iniciar o 3D. Feche a nota e tente novamente.','Branco','Azul-marinho','Azul','Ciano','Ciano claro'],
 de:['Platziere entdeckte Würfel und merke dir die Form.','Ziehe Würfel, um das Level als Miniatur nachzubauen.','WÜRFELVORRAT','Ziehe den Würfel in die Arbeitsfläche.','Einzeln platzieren','Reihe platzieren','NOTIZFARBEN','Farben dienen als Notiz und beeinflussen die Antwort nicht.','Rückgängig','Wiederholen','Auswahl löschen','Alles löschen','Drehung zurücksetzen','ANSICHT','Normal','Nur Kanten','Farben ausblenden','STEUERUNG','Ziehen: Würfel platzieren','Fläche ziehen: in diese Richtung erweitern','Rechts ziehen / leere Touch-Fläche: drehen','Mausrad / Pinch: zoomen','Klicken / tippen: auswählen','ZU DEN HINWEISEN','Nach einer falschen Antwort ist ein Hinweis einmal nutzbar. Nur richtig platzierte Notizwürfel leuchten. Andere bleiben weiß; fehlende Würfel werden nicht gezeigt.','Hinweis gesperrt','Hinweis nutzen','Hinweis verwendet','Notiz schließen','3D-Arbeitsfläche','3D konnte nicht starten. Schließe die Notiz und versuche es erneut.','Weiß','Dunkelblau','Blau','Cyan','Hellcyan'],
 fr:['Place les cubes découverts pour mémoriser la forme.','Fais glisser les cubes pour recréer le niveau en miniature.','RÉSERVE DE CUBES','Fais glisser le cube dans la zone de travail.','Placer un cube','Placement continu','COULEURS DES NOTES','Les couleurs servent de notes et ne changent pas la réponse.','Annuler','Rétablir','Supprimer la sélection','Tout supprimer','Réinitialiser la rotation','AFFICHAGE','Normal','Contours seuls','Masquer les couleurs','COMMANDES','Glisser : placer un cube','Glisser une face : prolonger dans cette direction','Glisser à droite / zone tactile vide : tourner','Molette / pincement : zoomer','Cliquer / toucher : sélectionner','À PROPOS DES INDICES','Après une erreur, un indice est utilisable une fois. Seuls les cubes bien placés dans ta note brillent. Les autres restent blancs ; les cubes manquants ne sont pas révélés.','Indice verrouillé','Utiliser l’indice','Indice utilisé','Fermer la note','Zone de travail 3D','Impossible de lancer la 3D. Ferme la note et réessaie.','Blanc','Bleu marine','Bleu','Cyan','Cyan clair']
};
export function memoTranslation(locale:Locale,key:string){const i=(memoKeys as readonly string[]).indexOf(key.replace(/^memo\./,''));return key.startsWith('memo.')&&i>=0?memoValues[locale]?.[i]??memoValues.en[i]:undefined;}
