import type {Locale} from '../types';
export const responsiveKeys=['game.time','game.menu','game.lookUp','game.thirdPerson','game.jump','game.move','stageSelect.title','stageSelect.all','stageSelect.alphabet','stageSelect.digits','stageSelect.shapes','game.stage','common.play','common.clear','answer.title','answer.remainingAttempts','answer.submit','answer.backToExploration','answer.incorrect','answer.failed','result.correct','result.stageClear','result.nextStage','result.retry','result.stageSelect','common.back','common.paused','how.touch.body','how.touch.move','how.touch.camera','how.touch.jump','how.touch.ladder','how.touch.lookUp','how.touch.answer','how.keyboard'] as const;
export const responsiveCopy:Record<Locale,readonly string[]>={
en:['TIME','MENU','LOOK UP','THIRD PERSON','JUMP','MOVE','STAGE SELECT','ALL','LETTERS','DIGITS','SHAPES','STAGE','PLAY','CLEAR','SELECT THE CORRECT SHAPE','REMAINING CHANCES','SUBMIT ANSWER','BACK TO EXPLORATION','INCORRECT · TRY AGAIN','NO CHANCES REMAIN','CORRECT!','STAGE {stage} CLEAR','NEXT STAGE','RETRY','STAGE SELECT','BACK','PAUSED','Touch controls','Drag on the left to move or turn.','Drag on the right to look around. Tap the camera button to switch view.','Tap JUMP to jump.','On a ladder, drag up/down to climb and left/right to move sideways. At the edge, left/right turns the camera.','Hold LOOK UP to look straight up.','Near the terminal, tap Answer, select a shape, then submit.','Keyboard controls (when available)'],
ja:['時間','メニュー','見上げる','三人称','ジャンプ','移動','ステージ選択','すべて','文字','数字','形','ステージ','プレイ','クリア','正しい形を選択','残り回答回数','回答する','探索に戻る','不正解です。もう一度選べます。','回答回数を使い切りました','正解！','ステージ {stage} クリア','次のステージ','再挑戦','ステージ選択','戻る','一時停止','タッチ操作','左側をドラッグして移動・旋回します。','右側をドラッグして視点操作。カメラボタンで視点を切り替えます。','ジャンプボタンをタップします。','梯子では上下ドラッグで昇降、左右ドラッグで横移動。端では視点が旋回します。','見上げるボタンを押している間、真上を確認できます。','端末の近くで「回答」をタップし、形を選んで回答します。','キーボード操作（接続している場合）'],
ko:['시간','메뉴','위 보기','3인칭','점프','이동','스테이지 선택','전체','문자','숫자','도형','스테이지','플레이','완료','올바른 모양을 선택하세요','남은 기회','답 제출','탐색으로 돌아가기','오답입니다. 다시 선택하세요.','기회를 모두 사용했습니다','정답!','스테이지 {stage} 클리어','다음 스테이지','다시 도전','스테이지 선택','뒤로','일시 정지','터치 조작','왼쪽을 드래그해 이동하거나 회전하세요.','오른쪽을 드래그해 둘러보세요. 카메라 버튼으로 시점을 바꿔요.','점프 버튼을 탭하세요.','사다리에서는 위아래로 드래그해 오르내리고 좌우로 이동해요. 끝에서는 시점이 회전해요.','위 보기 버튼을 누르는 동안 위를 볼 수 있어요.','단말기 근처에서 답하기를 탭하고 모양을 선택한 뒤 제출하세요.','키보드 조작 (연결된 경우)'],
'zh-CN':['时间','菜单','向上看','第三人称','跳跃','移动','选择关卡','全部','字母','数字','形状','关卡','开始','已完成','选择正确的形状','剩余机会','提交答案','返回探索','不正确，请再试一次','机会已用完','正确！','关卡 {stage} 完成','下一关','重试','选择关卡','返回','已暂停','触屏操作','在左侧拖动来移动或转向。','在右侧拖动来观察。点击镜头按钮切换视角。','点击跳跃按钮。','在梯子上，上下拖动可攀爬，左右拖动可横移。到达边缘后可旋转视角。','按住向上看按钮查看正上方。','靠近终端时点击回答，选择形状后提交。','键盘操作（已连接时）'],
'zh-TW':['時間','選單','向上看','第三人稱','跳躍','移動','選擇關卡','全部','字母','數字','形狀','關卡','開始','已完成','選擇正確的形狀','剩餘機會','提交答案','返回探索','不正確，請再試一次','機會已用完','正確！','關卡 {stage} 完成','下一關','重試','選擇關卡','返回','已暫停','觸控操作','在左側拖曳來移動或轉向。','在右側拖曳來觀察。點擊鏡頭按鈕切換視角。','點擊跳躍按鈕。','在梯子上，上下拖曳可攀爬，左右拖曳可橫移。到達邊緣後可旋轉視角。','按住向上看按鈕查看正上方。','靠近終端時點擊回答，選擇形狀後提交。','鍵盤操作（已連接時）'],
es:['TIEMPO','MENÚ','MIRAR ARRIBA','TERCERA PERSONA','SALTAR','MOVER','SELECCIONAR FASE','TODAS','LETRAS','NÚMEROS','FORMAS','FASE','JUGAR','COMPLETADA','ELIGE LA FORMA CORRECTA','INTENTOS RESTANTES','RESPONDER','VOLVER A EXPLORAR','INCORRECTO · INTÉNTALO DE NUEVO','NO QUEDAN INTENTOS','¡CORRECTO!','FASE {stage} COMPLETADA','SIGUIENTE FASE','REINTENTAR','SELECCIONAR FASE','VOLVER','PAUSA','Controles táctiles','Arrastra a la izquierda para moverte o girar.','Arrastra a la derecha para mirar. Toca el botón de cámara para cambiar la vista.','Toca Saltar para saltar.','En la escalera, arrastra arriba/abajo para subir o bajar, e izquierda/derecha para moverte de lado. En el borde giras la cámara.','Mantén pulsado Mirar arriba para ver sobre ti.','Cerca del terminal, toca Responder, elige una forma y confirma.','Teclado (si está conectado)'],
pt:['TEMPO','MENU','OLHAR ACIMA','TERCEIRA PESSOA','SALTAR','MOVER','SELECIONAR FASE','TODAS','LETRAS','NÚMEROS','FORMAS','FASE','JOGAR','CONCLUÍDA','ESCOLHA A FORMA CERTA','TENTATIVAS RESTANTES','RESPONDER','VOLTAR A EXPLORAR','INCORRETO · TENTE NOVAMENTE','NÃO RESTAM TENTATIVAS','CORRETO!','FASE {stage} CONCLUÍDA','PRÓXIMA FASE','TENTAR NOVAMENTE','SELECIONAR FASE','VOLTAR','PAUSA','Controlos táteis','Arraste à esquerda para mover ou virar.','Arraste à direita para olhar. Toque no botão da câmara para mudar a vista.','Toque em Saltar para saltar.','Na escada, arraste para cima/baixo para subir ou descer e para os lados para se deslocar. Na extremidade, a câmara roda.','Mantenha Olhar acima premido para ver por cima.','Perto do terminal, toque em Responder, escolha uma forma e confirme.','Teclado (se estiver ligado)'],
de:['ZEIT','MENÜ','HOCHSCHAUEN','DRITTE PERSON','SPRINGEN','BEWEGEN','LEVEL AUSWÄHLEN','ALLE','BUCHSTABEN','ZAHLEN','FORMEN','LEVEL','SPIELEN','GESCHAFFT','WÄHLE DIE RICHTIGE FORM','VERBLEIBENDE VERSUCHE','ANTWORTEN','WEITER ERKUNDEN','FALSCH · VERSUCHE ES ERNEUT','KEINE VERSUCHE ÜBRIG','RICHTIG!','LEVEL {stage} GESCHAFFT','NÄCHSTES LEVEL','ERNEUT VERSUCHEN','LEVEL AUSWÄHLEN','ZURÜCK','PAUSIERT','Touch-Steuerung','Ziehe links, um dich zu bewegen oder zu drehen.','Ziehe rechts, um dich umzusehen. Die Kamera-Taste wechselt die Ansicht.','Tippe zum Springen auf Springen.','Ziehe an der Leiter nach oben/unten zum Klettern und seitwärts zum Versetzen. Am Rand drehst du die Kamera.','Halte Hochschauen gedrückt, um direkt nach oben zu sehen.','Tippe am Terminal auf Antworten, wähle eine Form und bestätige.','Tastatur (falls angeschlossen)'],
fr:['TEMPS','MENU','REGARDER EN HAUT','TROISIÈME PERSONNE','SAUTER','BOUGER','CHOISIR UN NIVEAU','TOUS','LETTRES','CHIFFRES','FORMES','NIVEAU','JOUER','TERMINÉ','CHOISIS LA BONNE FORME','ESSAIS RESTANTS','RÉPONDRE','REPRENDRE L’EXPLORATION','INCORRECT · RÉESSAIE','PLUS AUCUN ESSAI','CORRECT !','NIVEAU {stage} TERMINÉ','NIVEAU SUIVANT','RÉESSAYER','CHOISIR UN NIVEAU','RETOUR','PAUSE','Commandes tactiles','Glisse à gauche pour te déplacer ou tourner.','Glisse à droite pour regarder. Touche le bouton caméra pour changer de vue.','Touche Sauter pour sauter.','Sur l’échelle, glisse en haut/bas pour monter ou descendre et sur les côtés pour te décaler. Au bord, la caméra tourne.','Maintiens Regarder en haut pour voir au-dessus.','Près du terminal, touche Répondre, choisis une forme et valide.','Clavier (si connecté)']
};
const resultCopy:Record<Locale,readonly [string,string]>={en:['ATTEMPTS','ALL STAGES CLEAR!'],ja:['回答回数','全ステージクリア！'],ko:['시도 횟수','모든 스테이지 클리어!'],'zh-CN':['回答次数','全部关卡完成！'],'zh-TW':['回答次數','全部關卡完成！'],es:['INTENTOS','¡TODAS LAS FASES COMPLETADAS!'],pt:['TENTATIVAS','TODAS AS FASES CONCLUÍDAS!'],de:['VERSUCHE','ALLE LEVEL GESCHAFFT!'],fr:['ESSAIS','TOUS LES NIVEAUX TERMINÉS !']};
export const homeSupplementKeys=['home.continueSub','home.newGameSub','home.stageSelectSub','home.howToPlaySub','home.playerProgress','home.progress','home.nextStage','home.bestTime','home.totalTime'] as const;
export const homeSupplement:Record<Locale,readonly string[]>={
en:['RESUME PROGRESS','START FROM STAGE 1','CHOOSE A STAGE','LEARN THE RULES','PLAYER PROGRESS','PROGRESS','NEXT STAGE','BEST TIME','TOTAL TIME'],
ja:['前回の続きから','ステージ1から始める','ステージを選ぶ','操作とルールを確認','プレイ進捗','進捗','次のステージ','ベストタイム','合計タイム'],
ko:['이어서 플레이','스테이지 1부터 시작','스테이지 고르기','조작과 규칙 확인','플레이 진행도','진행도','다음 스테이지','최고 기록','총 시간'],
'zh-CN':['继续上次进度','从第1关开始','挑选关卡','了解操作与规则','游戏进度','进度','下一关','最佳用时','总用时'],
'zh-TW':['繼續上次進度','從第1關開始','挑選關卡','了解操作與規則','遊戲進度','進度','下一關','最佳時間','總時間'],
es:['RETOMA TU PROGRESO','EMPIEZA EN LA FASE 1','ELIGE UNA FASE','CONTROLES Y REGLAS','TU PROGRESO','PROGRESO','SIGUIENTE FASE','MEJOR TIEMPO','TIEMPO TOTAL'],
pt:['RETOME O PROGRESSO','COMECE NA FASE 1','ESCOLHA UMA FASE','CONTROLOS E REGRAS','PROGRESSO','PROGRESSO','PRÓXIMA FASE','MELHOR TEMPO','TEMPO TOTAL'],
de:['SPIELE WEITER','BEGINNE MIT LEVEL 1','WÄHLE EIN LEVEL','STEUERUNG UND REGELN','SPIELFORTSCHRITT','FORTSCHRITT','NÄCHSTES LEVEL','BESTZEIT','GESAMTZEIT'],
fr:['REPRENDS TA PARTIE','COMMENCE AU NIVEAU 1','CHOISIS UN NIVEAU','COMMANDES ET RÈGLES','TA PROGRESSION','PROGRESSION','NIVEAU SUIVANT','MEILLEUR TEMPS','TEMPS TOTAL']};
export function responsiveTranslation(locale:Locale,key:string):string|undefined{if(key==='result.attempts')return resultCopy[locale][0];if(key==='result.allClear')return resultCopy[locale][1];const h=(homeSupplementKeys as readonly string[]).indexOf(key);if(h>=0)return homeSupplement[locale][h]??homeSupplement.en[h];const i=(responsiveKeys as readonly string[]).indexOf(key);return i<0?undefined:responsiveCopy[locale][i]??responsiveCopy.en[i];}
