import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {AudioManager} from '../src/audio/AudioManager';
import {AUDIO_MANIFEST,isApproved,type AudioSlot} from '../src/audio/manifest';
import {CubeMemoStore} from '../src/game/CubeMemo';
let starts=0,fetcher:ReturnType<typeof vi.fn>;
// Output protection is a native graph node; DSP is audited in a real browser.
class Context {state='suspended';currentTime=0;destination={};resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}close(){this.state='closed';return Promise.resolve();}decodeAudioData(){return Promise.resolve({});}createGain(){return{gain:{value:0,cancelScheduledValues(){},setTargetAtTime(){}},connect(){},disconnect(){}};}createBufferSource(){return{buffer:null,loop:false,playbackRate:{value:1},onended:null,connect(n:unknown){return n;},disconnect(){},start(){starts++;},stop(){}};}}
beforeEach(()=>{starts=0;const data=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v)});vi.stubGlobal('AudioContext',Context);vi.stubGlobal('location',{href:'http://localhost/',origin:'http://localhost'});fetcher=vi.fn(async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(0)}));vi.stubGlobal('fetch',fetcher);});afterEach(()=>vi.unstubAllGlobals());
Object.assign(Context.prototype,{createWaveShaper(){return {curve:null,connect(){},disconnect(){}};}});
function fixture(){const m=structuredClone(AUDIO_MANIFEST);for(const key of Object.keys(m) as AudioSlot[])m[key]={...m[key],url:'/fixture.wav',approved:true,rights:{source:'TEST ONLY',creator:'TEST',license:'TEST',commercial:true,redistribution:true,youtube:true,attribution:'none'}};return new AudioManager(m);}
it('ships thirteen original production slots and loads fifteen compressed files after unlock',async()=>{expect(Object.keys(AUDIO_MANIFEST)).toHaveLength(13);expect(Object.values(AUDIO_MANIFEST).every(isApproved)).toBe(true);const a=new AudioManager();a.playBGM('HOME');expect(fetcher).not.toHaveBeenCalled();await a.unlock();expect(fetcher).toHaveBeenCalledTimes(15);expect(a.snapshot().loaded).toBe(13);a.dispose();});
it('loads and starts after host unmutes a previously blocked unlock',async()=>{const a=fixture();a.playBGM('HOME');a.setHostEnabled(false);await a.unlock();expect(fetcher).not.toHaveBeenCalled();a.setHostEnabled(true);await vi.waitFor(()=>expect(a.snapshot().bgmVoices).toBe(1));expect(a.snapshot().loaded).toBe(13);a.dispose();});
it('batch placement schedules five bounded notes; pause cancels the entire batch',async()=>{const a=fixture();await a.unlock();a.emit('MEMO_CUBE_COMMIT',{count:5});expect(a.snapshot().seVoices).toBe(5);expect(starts).toBe(5);a.pause();expect(a.snapshot().seVoices).toBe(0);a.dispose();});
it('keeps BGM running across stages and bounds effect voices',async()=>{const a=fixture();a.playBGM('GAMEPLAY');await a.unlock();const n=starts;for(let i=0;i<20;i++)a.playBGM('GAMEPLAY');expect(starts).toBe(n);for(let i=0;i<100;i++)a.playSE('jump');expect(a.snapshot().seVoices).toBe(8);a.dispose();expect(a.snapshot().seVoices).toBe(0);});
it('separates toggles and persists preferences without progress writes',async()=>{const a=fixture();await a.unlock();a.playBGM('HOME');a.setBGMEnabled(false);a.playSE('jump');expect(a.snapshot().seVoices).toBe(1);a.setSEEnabled(false);a.setBGMEnabled(true);expect(a.snapshot().bgmVoices).toBe(1);expect(a.snapshot().seVoices).toBe(0);const restored=new AudioManager();expect(restored.bgmEnabled).toBe(true);expect(restored.seEnabled).toBe(false);expect(localStorage.getItem('icube-test-save')).toBeNull();a.dispose();});
it('does not resume while another pause reason or host mute remains',async()=>{const a=fixture();await a.unlock();a.pause('sdk');a.pause('visibility');a.resume('visibility');a.playSE('jump');expect(a.snapshot().seVoices).toBe(0);a.setHostEnabled(false);a.resume('sdk');expect(a.snapshot().hostEnabled).toBe(false);a.setHostEnabled(true);await Promise.resolve();a.playSE('jump');expect(a.snapshot().seVoices).toBe(1);a.pause();expect(a.snapshot().seVoices).toBe(0);a.dispose();});
it('bounds diagnostics and stops boost tails',async()=>{const a=fixture();await a.unlock();for(let i=0;i<160;i++)a.emit('BOOST_START');expect(a.events).toHaveLength(128);a.stopSE('boost');expect(a.snapshot().seVoices).toBe(0);a.dispose();});
it('failed fetch is nonfatal and cached instead of retried per event',async()=>{fetcher.mockRejectedValue(Error('fixture failure'));const warn=vi.spyOn(console,'warn').mockImplementation(()=>{});const a=fixture();await a.unlock();await a.unlock();expect(fetcher).toHaveBeenCalledTimes(13);expect(a.snapshot().loaded).toBe(0);a.dispose();warn.mockRestore();});
it('correct scene uses a distinct non-restarting BGM state',async()=>{const a=fixture();await a.unlock();a.playBGM('GAMEPLAY');a.playBGM('CORRECT_SCENE');const n=starts;a.playBGM('CORRECT_SCENE');expect(starts).toBe(n);expect(a.snapshot().bgmVoices).toBe(1);a.playBGM('HOME');expect(a.snapshot().bgm).toBe('HOME');a.dispose();});
it('placement emits committed count once; undo, redo, color and duplicate emit none',()=>{const s=new CubeMemoStore('audio-test',[[0,0,0]]),events:number[]=[];s.onPlacement=n=>events.push(n);s.add(1,0,0);s.addLine(1,0,0,'x',3);s.addLine(4,0,0,'x',5);s.undoOnce();s.redoOnce();s.color(s.cubes[1]!.id,'blue');s.add(1,0,0);expect(events).toEqual([1,3,5]);});
