import {it,expect,vi} from 'vitest';
import * as T from 'three';
import {parseCandidate} from '../src/game/glb/GLBCharacterVisual';
import {CharacterVisualSlot} from '../src/game/glb/CharacterVisualSlot';
import {AnimationState} from '../src/game/glb/AnimationState';
// Empty GLB container is a parser fixture, NOT a character or a production asset.
function fixture():ArrayBuffer{const str=JSON.stringify({asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:'Fixture only'}]});const json=new TextEncoder().encode(str.padEnd(Math.ceil(str.length/4)*4));const b=new ArrayBuffer(20+json.length),v=new DataView(b);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,b.byteLength,true);v.setUint32(12,json.length,true);v.setUint32(16,0x4e4f534a,true);new Uint8Array(b,20).set(json);return b;}
it('loads a GLB container while reporting all absent rig/clips, not accepting it as a formal model',async()=>{const v=await parseCandidate(fixture(),{clips:{}});expect(v.report.skinnedMeshes).toBe(0);expect(v.report.missingBones.length).toBeGreaterThan(10);expect(v.report.missingStates).toHaveLength(11);expect(v.play('JOG')).toBe(false);v.dispose();v.dispose();});
it('invalid GLB preserves fallback and never changes player position',async()=>{const fallback={root:new T.Group(),update:vi.fn()},slot=new CharacterVisualSlot(fallback),p=new T.Vector3(1,2,3);expect(await slot.preload(async()=>new ArrayBuffer(8),{clips:{}})).toBe(false);slot.update(p,1,1,.016);expect(fallback.root.visible).toBe(true);expect(fallback.update).toHaveBeenCalled();expect(p.toArray()).toEqual([1,2,3]);expect(slot.previewCandidate()).toBe(false);});
it('deduplicates preload, requires explicit viewer switch, supports fallback and disposal',async()=>{const f={root:new T.Group(),update:vi.fn()},slot=new CharacterVisualSlot(f),source=vi.fn(async()=>fixture());await Promise.all([slot.preload(source,{clips:{}}),slot.preload(source,{clips:{}})]);expect(source).toHaveBeenCalledTimes(1);expect(f.root.visible).toBe(true);expect(slot.previewCandidate()).toBe(true);expect(f.root.visible).toBe(false);slot.useFallback();expect(f.root.visible).toBe(true);slot.disposeCandidate();expect(slot.report).toBeNull();expect(slot.root.children).toHaveLength(1);});
it('timed-out fetch cannot stall fallback animation',async()=>{const f={root:new T.Group(),update:vi.fn()},s=new CharacterVisualSlot(f);expect(await s.preload(()=>new Promise(()=>{}),{clips:{}},5)).toBe(false);s.update(new T.Vector3(),0,0,.016);expect(f.update).toHaveBeenCalled();expect(s.lastError).toContain('timed out');});
it('maps takeoff, air, strong landing, moving recovery, turn and ladder without physics ownership',()=>{const s=new AnimationState(),f={speed:0,turnRate:0,airborne:false,climbing:false};expect(s.update(.016,f)).toBe('IDLE');expect(s.update(.016,{...f,airborne:true,verticalSpeed:6})).toBe('JUMP');expect(s.update(.016,{...f,airborne:true,verticalSpeed:-10})).toBe('AIRBORNE');expect(s.update(.016,f)).toBe('LAND_STRONG');expect(s.update(.35,{...f,speed:1})).toBe('JOG');expect(s.update(.3,{...f,turnRate:-1})).toBe('TURN_LEFT');expect(s.update(.016,{...f,climbing:true})).toBe('LADDER_IDLE');expect(s.update(.016,{...f,climbing:true,speed:1})).toBe('LADDER_CLIMB');});
