import type {FeedbackForm} from '../feedback/FeedbackService';
import {validateFeedback,submitFeedback} from '../feedback/FeedbackService';
import {feedbackIsEnabled} from '../feedback/FeedbackConfig';
import './feedback.css';
const btn=(text:string,cls='secondary')=>{const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=text;return b};
const rating=(name:string,labels:string[],required=true)=>{const field=document.createElement('fieldset');field.className='feedback-rating';const legend=document.createElement('legend');legend.textContent=name;field.append(legend);labels.forEach((label,i)=>{const l=document.createElement('label');const input=document.createElement('input');input.type='radio';input.name=name;input.value=String(i+1);input.required=required;l.append(input,document.createTextNode(label));field.append(l)});return field};
export class FeedbackModal{
  readonly root=document.createElement('section');private previous:Element|null=null;private keyHandler=(e:KeyboardEvent)=>{if(e.key==='Escape'){this.hide();return}if(e.key==='Tab'){const els=[...this.root.querySelectorAll<HTMLElement>('button,input,textarea,[tabindex]')].filter(e=>!e.hasAttribute('disabled'));if(!els.length)return;const i=els.indexOf(document.activeElement as HTMLElement);if(e.shiftKey&&i<=0){e.preventDefault();els.at(-1)?.focus()}else if(!e.shiftKey&&i===els.length-1){e.preventDefault();els[0]?.focus()}}};
  constructor(private readonly ids:{anonymousPlayerId:string;sessionId:string},private readonly onDismiss:()=>void,private readonly onSubmitted:()=>void){this.root.className='feedback-layer hidden';this.root.addEventListener('click',e=>{if(e.target===this.root){this.onDismiss();this.hide()}});}
  show(){if(!feedbackIsEnabled())return;this.previous=document.activeElement;this.renderIntro();this.root.classList.remove('hidden');document.addEventListener('keydown',this.keyHandler);(this.root.querySelector('button') as HTMLElement|null)?.focus();}
  hide(){this.root.classList.add('hidden');document.removeEventListener('keydown',this.keyHandler);(this.previous as HTMLElement|null)?.focus();}
  private shell(title:string){this.root.innerHTML='';const card=document.createElement('div');card.className='feedback-card';card.setAttribute('role','dialog');card.setAttribute('aria-modal','true');const h=document.createElement('h2');h.textContent=title;card.append(h);this.root.append(card);return card;}
  private renderIntro(){const card=this.shell('βプレイヤーアンケート');const p=document.createElement('p');p.textContent='i CUBE TESTをプレイしていただき、ありがとうございます。\n\n簡単なアンケートにぜひご協力ください。\n\nアンケートにお答えいただいた方には、正式版リリース後のお得な情報などを優先してお知らせする場合があります。\n\nメールアドレスの登録は任意です。';p.className='feedback-intro';const actions=document.createElement('div');actions.className='feedback-actions';const answer=btn('アンケートに答える','primary');answer.onclick=()=>this.renderForm();const later=btn('今はしない');later.onclick=()=>{this.onDismiss();this.hide()};actions.append(answer,later);card.append(p,actions);}
  private renderForm(){const card=this.shell('βフィードバック');const form=document.createElement('form');form.className='feedback-form';form.append(rating('操作は分かりやすかったですか？',['1','2','3','4','5']));const d=document.createElement('fieldset');const dl=document.createElement('legend');dl.textContent='ゲーム全体の難易度はいかがでしたか？';d.append(dl);([['very_easy','かなり簡単'],['easy','やや簡単'],['just_right','ちょうどよい'],['hard','やや難しい'],['very_hard','かなり難しい']] as const).forEach(([v,label])=>{const l=document.createElement('label');const i=document.createElement('input');i.type='radio';i.name='difficulty';i.value=v;i.required=true;l.append(i,document.createTextNode(label));d.append(l)});form.append(d);form.append(rating('i CUBE TESTを面白いと感じましたか？',['1','2','3','4','5']));const memo=rating('CUBE MEMOは使いやすかったですか？',['1','2','3','4','5'],false);const unused=document.createElement('label');const ui=document.createElement('input');ui.type='radio';ui.name='CUBE MEMOは使いやすかったですか？';ui.value='unused';unused.append(ui,document.createTextNode('使っていない'));memo.append(unused);form.append(memo);form.append(rating('また遊んでみたいと思いますか？',['1','2','3','4','5']));const comment=document.createElement('textarea');comment.name='comment';comment.maxLength=1000;comment.placeholder='気になった点・改善してほしい点（任意）';form.append(comment);const email=document.createElement('input');email.type='email';email.name='email';email.placeholder='メールアドレス（任意）';form.append(email);const consent=document.createElement('label');const ci=document.createElement('input');ci.type='checkbox';ci.name='consent';consent.append(ci,document.createTextNode('i CUBE TESTからのお知らせをメールで受け取ることに同意します'));form.append(consent);const privacy=document.createElement('small');privacy.textContent='アンケート回答はゲーム改善のために利用します。メールアドレスは任意で、お知らせ配信に同意した場合のみ連絡に使用します。';form.append(privacy);const error=document.createElement('p');error.className='feedback-error';error.setAttribute('aria-live','polite');const submit=btn('送信する','primary');submit.type='submit';form.append(error,submit);form.onsubmit=async e=>{e.preventDefault();const get=(name:string)=>form.querySelector<HTMLInputElement>(`input[name="${name}"]:checked`)?.value??'';const unusedValue=get('CUBE MEMOは使いやすかったですか？')==='unused';const data:FeedbackForm={ratingUsability:Number(get('操作は分かりやすかったですか？')),difficulty:get('difficulty') as FeedbackForm['difficulty'],ratingFun:Number(get('i CUBE TESTを面白いと感じましたか？')),ratingCubeMemo:unusedValue?null:Number(get('CUBE MEMOは使いやすかったですか？')),cubeMemoUnused:unusedValue,ratingReplay:Number(get('また遊んでみたいと思いますか？')),comment:comment.value.trim(),email:email.value.trim(),marketingConsent:ci.checked};const invalid=validateFeedback(data);if(invalid){error.textContent=invalid;return}submit.disabled=true;submit.textContent='送信中...';try{await submitFeedback(data,this.ids.anonymousPlayerId,this.ids.sessionId);this.onSubmitted();this.renderSuccess()}catch{submit.disabled=false;submit.textContent='送信する';error.textContent='送信できませんでした。通信環境を確認して、もう一度お試しください。'}};card.append(form);}
  private renderSuccess(){const card=this.shell('ご協力ありがとうございました！');const p=document.createElement('p');p.textContent='いただいたご意見は、今後のi CUBE TESTの改善に活用します。';const close=btn('閉じる','primary');close.onclick=()=>this.hide();card.append(p,close);close.focus();}
}

