import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {Character} from '../src/game/Character';
import {upgradeExplorerMaterials} from '../src/game/GameplayMaterials';
import {parseCandidate,type GLBCharacterVisual,type CandidateConfig} from '../src/game/glb/GLBCharacterVisual';
import {VISUAL_STATES,type VisualState} from '../src/game/glb/AnimationState';
const canvas=document.querySelector('canvas')!,renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color(0x172b3d);const camera=new T.PerspectiveCamera(42,1,.05,30);
scene.add(new T.HemisphereLight(0xe2f2ff,0x536878,.65));const key=new T.DirectionalLight(0xfff8ef,2.5);key.position.set(-3,6,4);key.castShadow=true;key.shadow.mapSize.setScalar(512);scene.add(key);const fill=new T.DirectionalLight(0xb4ddff,.4);fill.position.set(5,3,-5);scene.add(fill);const rim=new T.DirectionalLight(0x65d4ef,.8);rim.position.set(-3,2,5);scene.add(rim);
const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(room,.04,.1,100,{size:64});room.dispose();pmrem.dispose();scene.environment=env.texture;
const floor=new T.Mesh(new T.PlaneGeometry(12,12),new T.MeshStandardMaterial({color:0xe0e7eb,roughness:.64}));floor.rotation.x=-Math.PI/2;floor.position.y=-.008;floor.receiveShadow=true;scene.add(floor);
const procedural=new Character();upgradeExplorerMaterials(procedural.root);scene.add(procedural.root);procedural.root.traverse(o=>{if(o instanceof T.Mesh&&o.material instanceof T.MeshStandardMaterial)o.material.envMap=env.texture;});
let candidate:GLBCharacterVisual|null=null,helper:T.SkeletonHelper|null=null,generation=0,paused=false;const motion=document.querySelector<HTMLSelectElement>('#motion')!;for(const s of VISUAL_STATES)motion.add(new Option(s,s));
document.querySelector<HTMLButtonElement>('#pause')!.onclick=e=>{paused=!paused;(e.target as HTMLElement).textContent=paused?'再生':'一時停止';};
function discard(){helper?.geometry.dispose();if(helper){(helper.material as T.Material).dispose();helper.removeFromParent();}helper=null;candidate?.dispose();candidate=null;}
document.querySelector<HTMLInputElement>('#file')!.onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const mine=++generation;discard();const status=document.querySelector('#status')!,report=document.querySelector('#report')!;status.textContent='候補を検査中…';try{const config=JSON.parse(document.querySelector<HTMLTextAreaElement>('#config')!.value) as CandidateConfig;if(!config.clips||!Number.isFinite(config.height??1.42)||(config.height??1.42)<=0)throw Error('Invalid candidate configuration');const start=performance.now();const loaded=await parseCandidate(await file.arrayBuffer(),config);if(mine!==generation){loaded.dispose();return;}candidate=loaded;scene.add(loaded.root);helper=new T.SkeletonHelper(loaded.gltf.scene);scene.add(helper);report.textContent=JSON.stringify({...loaded.report,loadMs:performance.now()-start},null,2);status.textContent='未承認候補 — Rig / Material / Animation / 権利のUser QAが必要';}catch(error){if(mine===generation){status.textContent='候補読み込み失敗 — Gameplayは既存モデルを維持';report.textContent=String(error);}}};
let last=performance.now(),phase=0,frames=0,start=last,animationMs=0;const zero=new T.Vector3();
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(document.hidden)return;if(!paused)phase+=dt;const state=motion.value as VisualState;
 if(!paused){const t=performance.now();const climb=state.startsWith('LADDER'),air=state==='AIRBORNE'||state==='JUMP',land=state.startsWith('LAND');const cycle=phase%1.8;const landingAir=land&&cycle<.3;zero.y=landingAir?(state==='LAND_STRONG'?2:1)-cycle*6:0;
 procedural.update(zero,0,state==='JOG'||state==='LADDER_CLIMB'?1:0,dt,climb,state==='TURN_LEFT'?-1:state==='TURN_RIGHT'?1:0,air||landingAir);if(air)procedural.root.position.y=.15;
 if(candidate){candidate.play(state);candidate.tick(dt);}animationMs+=performance.now()-t;}
 const wire=document.querySelector<HTMLInputElement>('#wire')!.checked;for(const root of [procedural.root,candidate?.root])root?.traverse(o=>{if(o instanceof T.Mesh)for(const m of Array.isArray(o.material)?o.material:[o.material])if(m instanceof T.MeshStandardMaterial)m.wireframe=wire;});
 const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.floor(w*renderer.getPixelRatio())||canvas.height!==Math.floor(h*renderer.getPixelRatio()))renderer.setSize(w,h,false);camera.aspect=w/2/h;camera.updateProjectionMatrix();const view=document.querySelector<HTMLSelectElement>('#view')!.value;camera.position.set(...(view==='side'?[3,1,0]:view==='back'?[0,1,3]:view==='quarter'?[2,1.3,-2]:[0,1,-3]) as [number,number,number]);camera.lookAt(0,.75,0);
 renderer.setScissorTest(true);renderer.setViewport(0,0,w/2,h);renderer.setScissor(0,0,w/2,h);procedural.root.visible=true;if(candidate)candidate.root.visible=false;if(helper)helper.visible=false;renderer.render(scene,camera);
 renderer.setViewport(w/2,0,w/2,h);renderer.setScissor(w/2,0,w/2,h);procedural.root.visible=false;if(candidate)candidate.root.visible=true;if(helper)helper.visible=document.querySelector<HTMLInputElement>('#skeleton')!.checked;renderer.render(scene,camera);frames++;
 if(now-start>1000){document.querySelector('#metrics')!.textContent=`Viewer FPS ${(frames*1000/(now-start)).toFixed(1)} / animation CPU ${(animationMs/frames).toFixed(3)} ms per frame / renderer textures ${renderer.info.memory.textures}\n候補側の状態 ${state}: ${candidate?.config.clips[state]??'Clip未提供'}`;frames=0;animationMs=0;start=now;}
}
requestAnimationFrame(frame);window.addEventListener('pagehide',()=>{generation++;discard();env.dispose();renderer.dispose();});
